pub mod active_universe;
pub mod adaptive_quantiles;
pub mod arena_alloc;
pub mod atomic_float;
pub mod config;
pub mod feed_health;
pub mod genome;
pub mod genome_store;
pub mod horizon_policy;
pub mod paths;
pub mod position;
pub mod protection_health;
pub mod ring_buffer;
pub mod state;
pub mod state_continuity;
pub mod symbol_ranker_engine;
pub mod symbol_registry;
pub mod symbols;
pub mod temporal_spectrum;
pub mod tick_source;
pub mod zero_alloc_pool;
pub mod zero_copy_stream;

// Re-exportamos los componentes principales
pub use adaptive_quantiles::{AdaptiveQuantileEngine, P2Quantile};
pub use atomic_float::AtomicF64;
pub use config::QuantumConfig;
pub use position::{Position, PositionManager};
pub use state::{GlobalArena, ScalpState};
pub use tick_source::{TickEvent, TickSource};
