/* Generated by Cython 3.2.5 */

#ifndef __PYX_HAVE__core__metal__quantum_bridge
#define __PYX_HAVE__core__metal__quantum_bridge

#include "Python.h"

#ifndef __PYX_HAVE_API__core__metal__quantum_bridge

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int py_validate_topological_integrity(struct QuantumStateArena const *, size_t);
__PYX_EXTERN_C void fire_oracle(struct QuantumStateArena const *, struct TradeDecision *);

#endif /* !__PYX_HAVE_API__core__metal__quantum_bridge */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("quantum_bridge", PyInit_quantum_bridge) instead of calling PyInit_quantum_bridge directly from Python 3.5 */
PyMODINIT_FUNC PyInit_quantum_bridge(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"quantum_bridge\", PyInit_quantum_bridge) instead of calling PyInit_quantum_bridge directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"quantum_bridge\", PyInit_quantum_bridge) instead of calling PyInit_quantum_bridge directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"quantum_bridge\", PyInit_quantum_bridge) instead of calling PyInit_quantum_bridge directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_quantum_bridge_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_quantum_bridge() __PYX_WARN_IF_PyInit_quantum_bridge_INIT_CALLED(PyInit_quantum_bridge())
#endif

#endif /* !__PYX_HAVE__core__metal__quantum_bridge */
