//! # Evolutionary Templates Engine
//!
//! Generates strongly-typed, compilable Rust source code modules in `cerebro/cortex/`
//! based on parametric templates filled by Metacortex pain/trauma analysis.

use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq)]
pub enum WaveletType {
    Haar,
    Daubechies4,
    MexicanHat,
}

impl WaveletType {
    pub fn to_rust_expr(&self) -> &'static str {
        match self {
            WaveletType::Haar => "wavelet_haar",
            WaveletType::Daubechies4 => "wavelet_db4",
            WaveletType::MexicanHat => "wavelet_mexican_hat",
        }
    }
}

/// Parametric configuration for a new Wavelet Feature module
#[derive(Debug, Clone)]
pub struct WaveletFeatureParams {
    pub id: u64,
    pub wavelet_type: WaveletType,
    pub window_size: usize,
    pub threshold: f64,
    pub activation_factor: f64,
}

/// Parametric configuration for a Volume & Funding Rate Predictor
#[derive(Debug, Clone)]
pub struct VolumeFundingParams {
    pub id: u64,
    pub lookback_bars: usize,
    pub funding_weight: f64,
    pub volume_spike_multiplier: f64,
    pub decay_rate: f64,
}

/// Configuración paramétrica de una estrategia del CONTINUO TEMPORAL.
///
/// # U-ERR-9 (LA FÁBRICA GENERABA LA BIFURCACIÓN DENTRO)
///
/// Se llamaba `DualHorizonStrategyParams` y llevaba seis campos en dos mitades
/// espejo —`scalp_tp`/`swing_tp`, `scalp_sl`/`swing_sl`,
/// `min_scalp_volume`/`min_swing_trend_hurst`—. El código que la fábrica
/// EMITÍA contenía un `if is_scalp { … } else { … }`: cada estrategia nueva
/// que el metacórtex escribiera nacía con el binario de horizonte grabado
/// dentro. Una fábrica que reproduce el defecto lo multiplica.
///
/// Ahora la estrategia se parametriza por τ: `tau_ms` es el horizonte de
/// referencia de la estrategia y las geometrías (TP/SL) y los mínimos de
/// microestructura se evalúan como FUNCIONES CONTINUAS de la τ efectiva de
/// cada oportunidad, sin ramas.
#[derive(Debug, Clone)]
pub struct ContinuumStrategyParams {
    pub id: u64,
    /// Horizonte de referencia τ₀ de la estrategia, en ms. Es la escala
    /// temporal alrededor de la cual se calibran sus geometrías.
    pub tau_ref_ms: f64,
    /// Take-profit en τ₀, como fracción de precio.
    pub tp_at_tau_ref: f64,
    /// Stop-loss en τ₀, como fracción de precio.
    pub sl_at_tau_ref: f64,
    /// Exponente de difusión de la serie: relaciona la dispersión esperada
    /// con el horizonte vía σ(τ) ∝ τ^H. H = 0,5 es difusión browniana; H > 0,5
    /// es persistente y H < 0,5 antipersistente. Es el exponente de Hurst
    /// medido, no una constante elegida.
    pub hurst_exponent: f64,
    /// Volumen mínimo en USD exigido a τ₀. A otras τ se escala con el tiempo,
    /// porque el volumen esperado en una ventana crece linealmente con ella.
    pub min_volume_usd_at_tau_ref: f64,
}

pub struct EvolutionaryTemplateEngine {
    cortex_dir: PathBuf,
}

impl EvolutionaryTemplateEngine {
    pub fn new<P: AsRef<Path>>(cortex_dir: P) -> Self {
        let path = cortex_dir.as_ref().to_path_buf();
        if !path.exists() {
            let _ = fs::create_dir_all(&path);
        }
        Self { cortex_dir: path }
    }

    /// Generates a new Wavelet Feature source file in `cortex/`
    pub fn generate_wavelet_feature(
        &self,
        params: &WaveletFeatureParams,
    ) -> std::io::Result<PathBuf> {
        let file_name = format!("wavelet_feature_v{}.rs", params.id);
        let target_path = self.cortex_dir.join(&file_name);

        let code = format!(
            r#"//! Auto-generated by Metacortex: Wavelet Feature Engine v{id}
//! Wavelet: {wavelet:?}, Window: {window}, Threshold: {threshold}

pub struct FeatureWaveletRegimen_v{id} {{
    window_size: usize,
    threshold: f64,
    activation_factor: f64,
}}

impl FeatureWaveletRegimen_v{id} {{
    pub fn new() -> Self {{
        Self {{
            window_size: {window},
            threshold: {threshold:.6},
            activation_factor: {activation:.6},
        }}
    }}

    pub fn compute(&self, data: &[f64]) -> f64 {{
        if data.len() < self.window_size {{
            return 0.0;
        }}
        let slice = &data[data.len() - self.window_size..];
        let mean: f64 = slice.iter().sum::<f64>() / (slice.len() as f64);
        let variance: f64 = slice.iter().map(|&x| (x - mean).powi(2)).sum::<f64>() / (slice.len() as f64);
        let std_dev = variance.sqrt();

        let count_above = slice.iter().filter(|&&x| (x - mean).abs() > self.threshold * std_dev).count();
        (count_above as f64 / self.window_size as f64) * self.activation_factor
    }}
}}

#[no_mangle]
pub extern "C" fn compute_wavelet_v{id}(data_ptr: *const f64, len: usize) -> f64 {{
    if data_ptr.is_null() || len == 0 {{
        return 0.0;
    }}
    let slice = unsafe {{ std::slice::from_raw_parts(data_ptr, len) }};
    let feature = FeatureWaveletRegimen_v{id}::new();
    feature.compute(slice)
}}
"#,
            id = params.id,
            wavelet = params.wavelet_type,
            window = params.window_size,
            threshold = params.threshold,
            activation = params.activation_factor,
        );

        fs::write(&target_path, code)?;
        Ok(target_path)
    }

    /// Generates a Volume & Funding Predictor source file in `cortex/`
    pub fn generate_volume_funding_predictor(
        &self,
        params: &VolumeFundingParams,
    ) -> std::io::Result<PathBuf> {
        let file_name = format!("volumen_funding_predictor_v{}.rs", params.id);
        let target_path = self.cortex_dir.join(&file_name);

        let code = format!(
            r#"//! Auto-generated by Metacortex: Volume & Funding Rate Predictor v{id}

pub struct VolumeFundingPredictor_v{id} {{
    lookback_bars: usize,
    funding_weight: f64,
    volume_spike_multiplier: f64,
    decay_rate: f64,
}}

impl VolumeFundingPredictor_v{id} {{
    pub fn new() -> Self {{
        Self {{
            lookback_bars: {lookback},
            funding_weight: {funding_weight:.6},
            volume_spike_multiplier: {volume_spike:.6},
            decay_rate: {decay:.6},
        }}
    }}

    pub fn predict_pressure(&self, volumes: &[f64], funding_rate: f64) -> f64 {{
        if volumes.len() < self.lookback_bars {{
            return 0.0;
        }}
        let Recent = &volumes[volumes.len() - self.lookback_bars..];
        let avg_vol: f64 = Recent.iter().sum::<f64>() / (Recent.len() as f64);
        let last_vol = Recent.last().copied().unwrap_or(0.0);

        let vol_ratio = if avg_vol > 0.0 {{ last_vol / avg_vol }} else {{ 1.0 }};
        let vol_signal = (vol_ratio - self.volume_spike_multiplier).max(0.0);
        let funding_signal = funding_rate * self.funding_weight;

        (vol_signal + funding_signal) * (-self.decay_rate).exp()
    }}
}}

#[no_mangle]
pub extern "C" fn predict_volume_funding_v{id}(vols_ptr: *const f64, len: usize, funding: f64) -> f64 {{
    if vols_ptr.is_null() || len == 0 {{
        return 0.0;
    }}
    let slice = unsafe {{ std::slice::from_raw_parts(vols_ptr, len) }};
    let predictor = VolumeFundingPredictor_v{id}::new();
    predictor.predict_pressure(slice, funding)
}}
"#,
            id = params.id,
            lookback = params.lookback_bars,
            funding_weight = params.funding_weight,
            volume_spike = params.volume_spike_multiplier,
            decay = params.decay_rate,
        );

        fs::write(&target_path, code)?;
        Ok(target_path)
    }

    /// Genera en `cortex/` una estrategia PARAMETRIZADA POR τ.
    ///
    /// U-ERR-9: la versión anterior (`generate_dual_horizon_strategy`) emitía
    /// código con un `if is_scalp { … } else { … }` dentro y dos juegos de
    /// parámetros espejo. El código emitido ahora no tiene ninguna rama por
    /// banda: todas sus magnitudes son funciones continuas de la τ de cada
    /// oportunidad.
    ///
    /// Las dos leyes de escalado que se emiten se derivan de física medible,
    /// no de constantes elegidas:
    ///
    /// * **Geometría (TP/SL) ∝ σ(τ) = τ^H.** La dispersión de precio esperada
    ///   en una ventana crece con el horizonte según el exponente de difusión
    ///   H de la serie (H = 0,5 es el caso browniano). Un objetivo fijado a τ₀
    ///   equivale, a otra τ, a `tp₀ · (τ/τ₀)^H`.
    /// * **Volumen mínimo ∝ τ.** El volumen esperado en una ventana es la tasa
    ///   media de volumen por su duración: crece linealmente con el horizonte.
    ///
    /// La afinidad resultante decae con el DÉFICIT RELATIVO de liquidez —una
    /// magnitud adimensional— en vez de con un déficit absoluto en USD
    /// dividido por un millón, que era una constante sin dimensión física.
    pub fn generate_continuum_strategy(
        &self,
        params: &ContinuumStrategyParams,
    ) -> std::io::Result<PathBuf> {
        let file_name = format!("continuum_strategy_v{}.rs", params.id);
        let target_path = self.cortex_dir.join(&file_name);

        let code = format!(
            r#"//! Auto-generado por Metacortex: estrategia del continuo temporal v{id}
//!
//! Sin bifurcación por banda de horizonte: toda magnitud es función de la τ
//! de la oportunidad evaluada.

pub struct ContinuumStrategy_v{id} {{
    /// Horizonte de referencia τ₀ (ms) sobre el que se calibraron las geometrías.
    pub tau_ref_ms: f64,
    /// Take-profit en τ₀, fracción de precio.
    pub tp_at_tau_ref: f64,
    /// Stop-loss en τ₀, fracción de precio.
    pub sl_at_tau_ref: f64,
    /// Exponente de difusión H: σ(τ) ∝ τ^H (0,5 = browniano).
    pub hurst_exponent: f64,
    /// Volumen mínimo (USD) exigido en una ventana de τ₀.
    pub min_volume_usd_at_tau_ref: f64,
}}

impl ContinuumStrategy_v{id} {{
    pub fn new() -> Self {{
        Self {{
            tau_ref_ms: {tau_ref:.6},
            tp_at_tau_ref: {tp_ref:.6},
            sl_at_tau_ref: {sl_ref:.6},
            hurst_exponent: {hurst:.6},
            min_volume_usd_at_tau_ref: {min_vol:.6},
        }}
    }}

    /// Razón de escala temporal τ/τ₀, saneada.
    #[inline]
    fn tau_ratio(&self, tau_ms: f64) -> f64 {{
        if !tau_ms.is_finite() || tau_ms <= 0.0 || self.tau_ref_ms <= 0.0 {{
            return 1.0;
        }}
        tau_ms / self.tau_ref_ms
    }}

    /// Factor de difusión σ(τ)/σ(τ₀) = (τ/τ₀)^H. El exponente se acota al
    /// rango físico de un proceso de difusión ([0, 1]): H = 0 no difunde y
    /// H = 1 es propagación balística.
    #[inline]
    fn diffusion_scale(&self, tau_ms: f64) -> f64 {{
        let h = if self.hurst_exponent.is_finite() {{
            self.hurst_exponent.clamp(0.0, 1.0)
        }} else {{
            0.5
        }};
        self.tau_ratio(tau_ms).powf(h)
    }}

    /// Take-profit esperado a horizonte τ.
    #[inline]
    pub fn take_profit_at(&self, tau_ms: f64) -> f64 {{
        self.tp_at_tau_ref * self.diffusion_scale(tau_ms)
    }}

    /// Stop-loss esperado a horizonte τ.
    #[inline]
    pub fn stop_loss_at(&self, tau_ms: f64) -> f64 {{
        self.sl_at_tau_ref * self.diffusion_scale(tau_ms)
    }}

    /// Volumen mínimo exigible en una ventana de duración τ: la tasa de
    /// volumen es por unidad de tiempo, así que el umbral escala con τ.
    #[inline]
    pub fn min_volume_at(&self, tau_ms: f64) -> f64 {{
        self.min_volume_usd_at_tau_ref * self.tau_ratio(tau_ms)
    }}

    /// Afinidad de la estrategia con una oportunidad de horizonte τ y
    /// liquidez `volume_usd`, en [0, 1].
    ///
    /// Decae exponencialmente con el déficit RELATIVO de liquidez
    /// (`déficit / umbral`), que es adimensional: sin liquidez suficiente la
    /// afinidad tiende a 0; alcanzado el umbral vale 1.
    pub fn affinity(&self, tau_ms: f64, volume_usd: f64) -> f64 {{
        if !volume_usd.is_finite() || volume_usd < 0.0 {{
            return 0.0;
        }}
        let required = self.min_volume_at(tau_ms);
        if required <= 0.0 {{
            return 1.0;
        }}
        let deficit = required - volume_usd;
        if deficit <= 0.0 {{
            1.0
        }} else {{
            (-deficit / required).exp().clamp(0.0, 1.0)
        }}
    }}
}}
"#,
            id = params.id,
            tau_ref = params.tau_ref_ms,
            tp_ref = params.tp_at_tau_ref,
            sl_ref = params.sl_at_tau_ref,
            hurst = params.hurst_exponent,
            min_vol = params.min_volume_usd_at_tau_ref,
        );

        fs::write(&target_path, code)?;
        Ok(target_path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn directorio_temporal(prefijo: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "{}_{}",
            prefijo,
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let _ = fs::create_dir_all(&dir);
        dir
    }

    /// U-ERR-9 — LA FÁBRICA NO REPRODUCE EL BINARIO DE HORIZONTE.
    ///
    /// Este test FALLA con el código viejo: `generate_dual_horizon_strategy`
    /// emitía literalmente `pub fn compute_affinity_tensor(&self, is_scalp:
    /// bool, …)` con un `if is_scalp { … } else { … }` dentro, de modo que
    /// cada estrategia que el metacórtex escribiera nacía con la bifurcación
    /// grabada. Se inspecciona el CÓDIGO EMITIDO, que es el artefacto que
    /// importa: ni una etiqueta de banda, ni un parámetro booleano de
    /// horizonte; en su lugar, las magnitudes son funciones de τ.
    #[test]
    fn u_err_9_el_codigo_emitido_no_contiene_bifurcacion_por_banda() {
        let dir = directorio_temporal("cortex_continuo");
        let engine = EvolutionaryTemplateEngine::new(&dir);

        let params = ContinuumStrategyParams {
            id: 42,
            tau_ref_ms: 30_000.0,
            tp_at_tau_ref: 0.004,
            sl_at_tau_ref: 0.002,
            hurst_exponent: 0.5,
            min_volume_usd_at_tau_ref: 250_000.0,
        };

        let ruta = engine
            .generate_continuum_strategy(&params)
            .expect("la fábrica debe emitir el fichero");
        let codigo = fs::read_to_string(&ruta).expect("el fichero emitido debe leerse");
        let bajo = codigo.to_ascii_lowercase();

        assert!(
            !bajo.contains("scalp") && !bajo.contains("swing"),
            "el código emitido arrastra etiquetas de banda"
        );
        assert!(
            !bajo.contains("is_scalp") && !bajo.contains("dual_horizon"),
            "el código emitido conserva el parámetro de bifurcación"
        );
        // Y sí lleva la parametrización del continuo.
        assert!(codigo.contains("tau_ms"), "el código emitido debe recibir τ");
        assert!(
            codigo.contains("fn take_profit_at") && codigo.contains("fn min_volume_at"),
            "las geometrías y los mínimos deben ser funciones de τ"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    /// U-ERR-9 — LAS LEYES DE ESCALADO EMITIDAS SON LAS DECLARADAS.
    ///
    /// Comprueba sobre el texto emitido que la geometría escala con el factor
    /// de difusión (σ(τ) ∝ τ^H) y el volumen mínimo con la duración de la
    /// ventana, que es lo que justifica que no haya bandas: una sola ley
    /// cubre todo el continuo.
    #[test]
    fn u_err_9_las_magnitudes_escalan_con_tau() {
        let dir = directorio_temporal("cortex_escalado");
        let engine = EvolutionaryTemplateEngine::new(&dir);

        let params = ContinuumStrategyParams {
            id: 7,
            tau_ref_ms: 60_000.0,
            tp_at_tau_ref: 0.01,
            sl_at_tau_ref: 0.005,
            hurst_exponent: 0.5,
            min_volume_usd_at_tau_ref: 100_000.0,
        };
        let ruta = engine.generate_continuum_strategy(&params).unwrap();
        let codigo = fs::read_to_string(&ruta).unwrap();

        assert!(
            codigo.contains("self.tp_at_tau_ref * self.diffusion_scale(tau_ms)"),
            "el take-profit debe escalar con el factor de difusión"
        );
        assert!(
            codigo.contains("self.min_volume_usd_at_tau_ref * self.tau_ratio(tau_ms)"),
            "el volumen mínimo debe escalar linealmente con τ"
        );
        assert!(
            codigo.contains("self.tau_ratio(tau_ms).powf(h)"),
            "el factor de difusión debe ser (τ/τ₀)^H"
        );
        // Los parámetros se inyectan tal cual, sin mitades espejo.
        assert!(codigo.contains("tau_ref_ms: 60000.000000"));
        assert!(codigo.contains("hurst_exponent: 0.500000"));

        let _ = fs::remove_dir_all(&dir);
    }
}
