//! # Evolutionary Templates Engine
//!
//! Generates strongly-typed, compilable Rust source code modules in `cerebro/cortex/`
//! based on parametric templates filled by Metacortex pain/trauma analysis.

use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq)]
pub enum WaveletType {
    Haar,
    Daubechies4,
    MexicanHat,
}

impl WaveletType {
    pub fn to_rust_expr(&self) -> &'static str {
        match self {
            WaveletType::Haar => "wavelet_haar",
            WaveletType::Daubechies4 => "wavelet_db4",
            WaveletType::MexicanHat => "wavelet_mexican_hat",
        }
    }
}

/// Parametric configuration for a new Wavelet Feature module
#[derive(Debug, Clone)]
pub struct WaveletFeatureParams {
    pub id: u64,
    pub wavelet_type: WaveletType,
    pub window_size: usize,
    pub threshold: f64,
    pub activation_factor: f64,
}

/// Parametric configuration for a Volume & Funding Rate Predictor
#[derive(Debug, Clone)]
pub struct VolumeFundingParams {
    pub id: u64,
    pub lookback_bars: usize,
    pub funding_weight: f64,
    pub volume_spike_multiplier: f64,
    pub decay_rate: f64,
}

/// Parametric configuration for a Scalp/Swing Dual Horizon Strategy
#[derive(Debug, Clone)]
pub struct DualHorizonStrategyParams {
    pub id: u64,
    pub scalp_tp: f64,
    pub scalp_sl: f64,
    pub swing_tp: f64,
    pub swing_sl: f64,
    pub min_scalp_volume: f64,
    pub min_swing_trend_hurst: f64,
}

pub struct EvolutionaryTemplateEngine {
    cortex_dir: PathBuf,
}

impl EvolutionaryTemplateEngine {
    pub fn new<P: AsRef<Path>>(cortex_dir: P) -> Self {
        let path = cortex_dir.as_ref().to_path_buf();
        if !path.exists() {
            let _ = fs::create_dir_all(&path);
        }
        Self { cortex_dir: path }
    }

    /// Generates a new Wavelet Feature source file in `cortex/`
    pub fn generate_wavelet_feature(
        &self,
        params: &WaveletFeatureParams,
    ) -> std::io::Result<PathBuf> {
        let file_name = format!("wavelet_feature_v{}.rs", params.id);
        let target_path = self.cortex_dir.join(&file_name);

        let code = format!(
            r#"//! Auto-generated by Metacortex: Wavelet Feature Engine v{id}
//! Wavelet: {wavelet:?}, Window: {window}, Threshold: {threshold}

pub struct FeatureWaveletRegimen_v{id} {{
    window_size: usize,
    threshold: f64,
    activation_factor: f64,
}}

impl FeatureWaveletRegimen_v{id} {{
    pub fn new() -> Self {{
        Self {{
            window_size: {window},
            threshold: {threshold:.6},
            activation_factor: {activation:.6},
        }}
    }}

    pub fn compute(&self, data: &[f64]) -> f64 {{
        if data.len() < self.window_size {{
            return 0.0;
        }}
        let slice = &data[data.len() - self.window_size..];
        let mean: f64 = slice.iter().sum::<f64>() / (slice.len() as f64);
        let variance: f64 = slice.iter().map(|&x| (x - mean).powi(2)).sum::<f64>() / (slice.len() as f64);
        let std_dev = variance.sqrt();

        let count_above = slice.iter().filter(|&&x| (x - mean).abs() > self.threshold * std_dev).count();
        (count_above as f64 / self.window_size as f64) * self.activation_factor
    }}
}}

#[no_mangle]
pub extern "C" fn compute_wavelet_v{id}(data_ptr: *const f64, len: usize) -> f64 {{
    if data_ptr.is_null() || len == 0 {{
        return 0.0;
    }}
    let slice = unsafe {{ std::slice::from_raw_parts(data_ptr, len) }};
    let feature = FeatureWaveletRegimen_v{id}::new();
    feature.compute(slice)
}}
"#,
            id = params.id,
            wavelet = params.wavelet_type,
            window = params.window_size,
            threshold = params.threshold,
            activation = params.activation_factor,
        );

        fs::write(&target_path, code)?;
        Ok(target_path)
    }

    /// Generates a Volume & Funding Predictor source file in `cortex/`
    pub fn generate_volume_funding_predictor(
        &self,
        params: &VolumeFundingParams,
    ) -> std::io::Result<PathBuf> {
        let file_name = format!("volumen_funding_predictor_v{}.rs", params.id);
        let target_path = self.cortex_dir.join(&file_name);

        let code = format!(
            r#"//! Auto-generated by Metacortex: Volume & Funding Rate Predictor v{id}

pub struct VolumeFundingPredictor_v{id} {{
    lookback_bars: usize,
    funding_weight: f64,
    volume_spike_multiplier: f64,
    decay_rate: f64,
}}

impl VolumeFundingPredictor_v{id} {{
    pub fn new() -> Self {{
        Self {{
            lookback_bars: {lookback},
            funding_weight: {funding_weight:.6},
            volume_spike_multiplier: {volume_spike:.6},
            decay_rate: {decay:.6},
        }}
    }}

    pub fn predict_pressure(&self, volumes: &[f64], funding_rate: f64) -> f64 {{
        if volumes.len() < self.lookback_bars {{
            return 0.0;
        }}
        let Recent = &volumes[volumes.len() - self.lookback_bars..];
        let avg_vol: f64 = Recent.iter().sum::<f64>() / (Recent.len() as f64);
        let last_vol = Recent.last().copied().unwrap_or(0.0);

        let vol_ratio = if avg_vol > 0.0 {{ last_vol / avg_vol }} else {{ 1.0 }};
        let vol_signal = (vol_ratio - self.volume_spike_multiplier).max(0.0);
        let funding_signal = funding_rate * self.funding_weight;

        (vol_signal + funding_signal) * (-self.decay_rate).exp()
    }}
}}

#[no_mangle]
pub extern "C" fn predict_volume_funding_v{id}(vols_ptr: *const f64, len: usize, funding: f64) -> f64 {{
    if vols_ptr.is_null() || len == 0 {{
        return 0.0;
    }}
    let slice = unsafe {{ std::slice::from_raw_parts(vols_ptr, len) }};
    let predictor = VolumeFundingPredictor_v{id}::new();
    predictor.predict_pressure(slice, funding)
}}
"#,
            id = params.id,
            lookback = params.lookback_bars,
            funding_weight = params.funding_weight,
            volume_spike = params.volume_spike_multiplier,
            decay = params.decay_rate,
        );

        fs::write(&target_path, code)?;
        Ok(target_path)
    }

    /// Generates a Dual Horizon Scalp/Swing strategy source file in `cortex/`
    pub fn generate_dual_horizon_strategy(
        &self,
        params: &DualHorizonStrategyParams,
    ) -> std::io::Result<PathBuf> {
        let file_name = format!("dual_horizon_strategy_v{}.rs", params.id);
        let target_path = self.cortex_dir.join(&file_name);

        let code = format!(
            r#"//! Auto-generated by Metacortex: Dual Horizon Strategy v{id}

pub struct DualHorizonStrategy_v{id} {{
    pub scalp_tp: f64,
    pub scalp_sl: f64,
    pub swing_tp: f64,
    pub swing_sl: f64,
    pub min_scalp_volume: f64,
    pub min_swing_trend_hurst: f64,
}}

impl DualHorizonStrategy_v{id} {{
    pub fn new() -> Self {{
        Self {{
            scalp_tp: {scalp_tp:.6},
            scalp_sl: {scalp_sl:.6},
            swing_tp: {swing_tp:.6},
            swing_sl: {swing_sl:.6},
            min_scalp_volume: {min_scalp_vol:.6},
            min_swing_trend_hurst: {min_swing_hurst:.6},
        }}
    }}

    pub fn compute_affinity_tensor(&self, is_scalp: bool, hurst: f64, volume_usd: f64) -> f64 {{
        if is_scalp {{
            let deficit = self.min_scalp_volume - volume_usd;
            if deficit <= 0.0 {{
                1.0
            }} else {{
                // Asymptotic decay for scalp volume shortage
                (-deficit / 1_000_000.0).exp()
            }}
        }} else {{
            let deficit = self.min_swing_trend_hurst - hurst;
            if deficit <= 0.0 {{
                1.0
            }} else {{
                // Asymptotic decay for swing hurst shortage
                (-deficit * 10.0).exp()
            }}
        }}
    }}
}}
"#,
            id = params.id,
            scalp_tp = params.scalp_tp,
            scalp_sl = params.scalp_sl,
            swing_tp = params.swing_tp,
            swing_sl = params.swing_sl,
            min_scalp_vol = params.min_scalp_volume,
            min_swing_hurst = params.min_swing_trend_hurst,
        );

        fs::write(&target_path, code)?;
        Ok(target_path)
    }
}
