import sys
import os

_project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from core.backtest_infra import fetch_binance_data
from config import Config
from strategies.components.feature_engineering import FeatureEngineering
import datetime

def audit_data_flow():
    print("🚀 [AUDIT] Starting Data Flow Integrity Audit...")
    symbol = "BTC/USDT"
    print(f"📥 Loading recent data for {symbol}...")
    
    # Simulate production data fetch
    df = fetch_binance_data(symbol, days=2, end_time=None)
    
    if df is None or df.is_empty():
        print("❌ [FATAL] Data is EMPTY. Flow is broken at source.")
        return
        
    print(f"✅ Data fetched successfully: {len(df)} rows.")
    print("📊 Sample Data columns:", df.columns)
    
    # Check for NaNs in critical columns
    for col in ['open', 'high', 'low', 'close', 'volume']:
        nan_count = df[col].is_null().sum()
        if nan_count > 0:
            print(f"⚠️ [WARNING] Column {col} has {nan_count} NaNs.")
            
    print("\n⚙️ Processing through Feature Engineering...")
    fe = FeatureEngineering()
    
    features_df = fe.prepare_features(df, symbol=symbol)
    
    if features_df is None or features_df.is_empty():
        print("❌ [FATAL] Feature Engineering returned empty dataframe.")
        return
        
    print(f"✅ Features generated successfully: {len(features_df)} rows.")
    
    # Check for ZOMBIE FEATURES (all zeros or NaNs)
    zombie_features = []
    for col in features_df.columns:
        if col in ['timestamp', 'open', 'high', 'low', 'close', 'volume']:
            continue
            
        # Ignore NaNs generated by rolling windows at the beginning
        valid_data = features_df[col].drop_nulls()
        if valid_data.is_empty():
            zombie_features.append(col)
        elif (valid_data == 0).all():
            zombie_features.append(col + " (ALL ZEROS)")
            
    if zombie_features:
        print(f"⚠️ [WARNING] Detected {len(zombie_features)} ZOMBIE features:")
        for z in zombie_features:
            print(f"   - {z}")
    else:
        print("✅ No Zombie features detected. Data flow is HEALTHY.")
        
    print("\n✅ Audit Complete.")

if __name__ == "__main__":
    audit_data_flow()
